export const language = {
  amount: `Amount`,
  arTokens: `AR`,
  arBalance: `AR Balance`,
  burn: `Burn`,
  burnDescription: `Easy way to burn <span>AR</span> for <span>U</span>`,
  burnFailure: `Burn Failed`,
  burnSuccess: `Burn Initiated`,
  claim: `Claim`,
  claimDescription: `Claim <span>U</span>`,
  claimsEmpty: `Nothing to claim`,
  claimRecipientPlaceholder: `Address`,
  claimSuccess: `Successfully claimed`,
  close: `Close`,
  connect: `Connect`,
  connectWallet: `Connect a wallet`,
  copied: `Copied!`,
  copyAddress: `Copy Address`,
  disconnect: `Disconnect`,
  docs: `Docs`,
  expires: `Expires`,
  fetching: `Fetching`,
  finalizeBurn: `Finalize Burn`,
  from: `From`,
  loading: `Loading`,
  mint: `Mint`,
  mintDescription: `To finalize a mint request, the mint function must be run on the Sequencer contract. Any wallet can do this at anytime.`,
  mintExecuted: `Mint Executed`,
  pageNotFound: `Page Not Found`,
  pollingTx: `Pending Tx`,
  qty: `Qty`,
  u: `U`,
  uBalance: `U Balance`,
  uClaimed: `U Claimed`,
  uClaimError: `Error claiming U`,
  requestQueue: `Ready To Finalize`,
  requestTransaction: `Request Transaction`,
  target: `Target`,
  to: `To`,
  transfer: `Transfer`,
  transferDescription: `Easy way to transfer <span>U</span> between accounts`,
  transferRecipientPlaceholder: `Address`,
  transferFailure: `Transfer failed`,
  transferSuccess: `Transfer Successfully Sent`,
};
