export const language = {
  amount: `Amount`,
  arTokens: `AR`,
  arBalance: `AR Balance`,
  burn: `Burn`,
  burnDescription: `Easy way to burn <span>AR</span> for <span>RebAR</span>`,
  burnFailure: `Burn Failed`,
  burnSuccess: `Burn Initiated`,
  claim: `Claim`,
  claimDescription: `Claim <span>RebAR</span>`,
  claimsEmpty: `Nothing to claim`,
  claimRecipientPlaceholder: `Address`,
  claimSuccess: `Successfully claimed`,
  close: `Close`,
  connect: `Connect`,
  connectWallet: `Connect a wallet`,
  copied: `Copied!`,
  copyAddress: `Copy Address`,
  disconnect: `Disconnect`,
  docs: `Docs`,
  expires: `Expires`,
  faq: {
    header: `FAQ`,
    list: [
      {
        q: `How long does it usually take to be able to mint RebAR?`,
        a: `When you burn your AR tokens, you are posting a L1 transaction.  It will take ~15 minutes for the transaction to be confirmed. The transaction can be finalized anytime after that.`,
      },
      {
        q: `Why is there 2 steps in burning an asset?`,
        a: `In order to prevent transfers from happening on L1 and L2, the contract was split in 2. Burning AR must be an L1 transaction, so mint requests get added to a request queue at the time of the burn.  When the transaction is confirmed, the user can finalize the mint on the L2 contract. This will read the request from the queue, and process the request.`,
      },
      {
        q: `What is Transfer for?`,
        a: `Transfer allows the L2 contract to transfer tokens from wallet to wallet in seconds on the Permaweb.`,
      },
      {
        q: `What is Claim for?`,
        a: `Claim is one part of the Foreign Call Protocol (FCP). It allows contracts to create transfers that can be claimed.  If a contract creates a transfer for a wallet, the tranfer can be claimed in the claim panel.`,
      },
    ],
  },
  fetching: `Fetching`,
  finalizeBurn: `Finalize Burn`,
  from: `From`,
  loading: `Loading`,
  mint: `Mint`,
  mintDescription: `To finalize a mint request, the mint function must be run on the Sequencer contract. Any wallet can do this at anytime.`,
  mintExecuted: `Mint Executed`,
  pageNotFound: `Page Not Found`,
  qty: `Qty`,
  rebar: `RebAR`,
  rebarBalance: `RebAR Balance`,
  rebarClaimed: `RebAR Claimed`,
  rebarClaimError: `Error claiming RebAR`,
  requestQueue: `Ready To Finalize`,
  requestTransaction: `Request Transaction`,
  target: `Target`,
  to: `To`,
  transfer: `Transfer`,
  transferDescription: `Easy way to transfer <span>RebAR</span> between accounts`,
  transferRecipientPlaceholder: `Address`,
  transferFailure: `Transfer failed`,
  transferSuccess: `Transfer Successfully Sent`,
};
