export const language = {
  amount: `Amount`,
  arTokens: `AR`,
  arBalance: `AR Balance`,
  burn: `Burn`,
  burnDescription: `Easy way to burn <span>AR</span> for <span>RebAR</span>`,
  burnFailure: `Burn Failed`,
  burnSuccess: `Burn Initiated`,
  claim: `Claim`,
  claimDescription: `Claim <span>RebAR</span>`,
  claimsEmpty: `Nothing to claim`,
  claimRecipientPlaceholder: `Address`,
  claimSuccess: `Successfully claimed`,
  close: `Close`,
  connect: `Connect`,
  connectWallet: `Connect a wallet`,
  copied: `Copied!`,
  copyAddress: `Copy Address`,
  disconnect: `Disconnect`,
  docs: `Docs`,
  expires: `Expires`,
  faq: {
    header: `FAQ`,
    list: [
      {
        q: `How long does it usually take to be able to claim rebAR?`,
        a: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus felis non tellus porttitor, vel mattis lectus ultrices. Donec iaculis augue a ultricies mollis. Nulla viverra nibh sit amet magna tempor, id consequat massa aliquet. Vivamus tristique cursus magna, non fringilla ex fermentum vitae.`,
      },
      {
        q: `Why is there 2 steps in burning an asset?`,
        a: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus felis non tellus porttitor, vel mattis lectus ultrices. Donec iaculis augue a ultricies mollis. Nulla viverra nibh sit amet magna tempor, id consequat massa aliquet. Vivamus tristique cursus magna, non fringilla ex fermentum vitae.`,
      },
      {
        q: `What is Transfer for?`,
        a: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus felis non tellus porttitor, vel mattis lectus ultrices. Donec iaculis augue a ultricies mollis. Nulla viverra nibh sit amet magna tempor, id consequat massa aliquet. Vivamus tristique cursus magna, non fringilla ex fermentum vitae.`,
      },
      {
        q: `What is Claim for?`,
        a: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus felis non tellus porttitor, vel mattis lectus ultrices. Donec iaculis augue a ultricies mollis. Nulla viverra nibh sit amet magna tempor, id consequat massa aliquet. Vivamus tristique cursus magna, non fringilla ex fermentum vitae.`,
      },
    ],
  },
  fetching: `Fetching`,
  finalizeBurn: `Finalize Burn`,
  from: `From`,
  loading: `Loading`,
  mint: `Mint`,
  mintDescription: `To finalize a mint request, the mint function must be run on the Sequencer contract. Any wallet can do this at anytime.`,
  mintExecuted: `Mint Executed`,
  pageNotFound: `Page Not Found`,
  qty: `Qty`,
  rebar: `RebAR`,
  rebarBalance: `RebAR Balance`,
  rebarClaimed: `RebAR Claimed`,
  rebarClaimError: `Error claiming RebAR`,
  requestQueue: `Ready To Finalize`,
  requestTransaction: `Request Transaction`,
  target: `Target`,
  to: `To`,
  transfer: `Transfer`,
  transferDescription: `Easy way to transfer <span>RebAR</span> between accounts`,
  transferRecipientPlaceholder: `Address`,
  transferFailure: `Transfer failed`,
  transferSuccess: `Transfer Successfully Sent`,
};
